# Generated by Django 5.2.16 on 2026-07-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_diaryentry_rating_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfitem',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
