# Generated by Django 5.2.16 on 2026-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_diaryentry_date_started_shelfitem_started_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='featured_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
